export const COMUNAS_CHILE = [
  "Algarrobo", "Alhué", "Alto Bío Bío", "Alto del Carmen", "Alto Hospicio", 
  "Ancud", "Andacollo", "Angol", "Antofagasta", "Antuco", "Arauco", "Arica", 
  "Buin", "Bulnes", "Cabildo", "Cabo de Hornos", "Cabrero", "Calama", "Calbuco", 
  "Caldera", "Calera de Tango", "Calle Larga", "Camarones", "Canela", "Cañete", 
  "Carahue", "Cartagena", "Casablanca", "Castro", "Catemu", "Cauquenes", 
  "Cerrillos", "Cerro Navia", "Chaitén", "Chanco", "Chañaral", "Chépica", 
  "Chiguayante", "Chile Chico", "Chillán", "Chillán Viejo", "Chimbarongo", 
  "Cholchol", "Chonchi", "Cisnes", "Cobquecura", "Cochamó", "Cochrane", 
  "Codegua", "Coelemu", "Coyhaique", "Coihueco", "Coinco", "Colbún", "Colchane", 
  "Colina", "Collipulli", "Coltauco", "Combarbalá", "Concepción", "Conchalí", 
  "Concón", "Constitución", "Contulmo", "Copiapó", "Coquimbo", "Coronel", 
  "Corral", "Cunco", "Curacautín", "Curacaví", "Curaco De Vélez", "Curanilahue", 
  "Curarrehue", "Curepto", "Curicó", "Dalcahue", "Diego de Almagro", "Doñihue", 
  "El Bosque", "El Carmen", "El Monte", "El Quisco", "El Tabo", "Empedrado", 
  "Ercilla", "Estación Central", "Florida", "Freire", "Freirina", "Fresia", 
  "Frutillar", "Futaleufú", "Futrono", "Galvarino", "General Lagos", "Gorbea", 
  "Graneros", "Hijuelas", "Hualaihué", "Hualañé", "Hualpén", "Hualqui", "Huara", 
  "Huasco", "Huechuraba", "Illapel", "Independencia", "Iquique", "Isla de Maipo", 
  "La Calera", "La Cisterna", "La Cruz", "La Estrella", "La Florida", "La Granja", 
  "La Higuera", "La Ligua", "La Pintana", "La Reina", "La Serena", "La Unión", 
  "Lago Ranco", "Lago Verde", "Laja", "Lampa", "Lanco", "Las Cabras", "Las Condes", 
  "Lautaro", "Lebu", "Licantén", "Limache", "Linares", "Litueche", "Llaillay", 
  "Llanquihue", "Lo Barnechea", "Lo espejo", "Lo Prado", "Lolol", "Loncoche", 
  "Longaví", "Lonquimay", "Los Álamos", "Los Andes", "Los Ángeles", "Los lagos", 
  "Los Muermos", "Los Sauces", "Los Vilos", "Lota", "Lumaco", "Machalí", "Macul", 
  "Máfil", "Maipú", "Malloa", "Marchihue", "María Pinto", "Mariquina", "Maule", 
  "Maullín", "Mejillones", "Melipeuco", "Melipilla", "Molina", "Monte Patria", 
  "Mostazal", "Mulchén", "Nacimiento", "Nancagua", "Natales", "Navidad", 
  "Negrete", "Ninhue", "Nogales", "Nueva Imperial", "Ñiquén", "Ñuñoa", "Olivar", 
  "Olmué", "Osorno", "Ovalle", "Padre Hurtado", "Padre Las Casas", "Paihuano", 
  "Paillaco", "Paine", "Palena", "Palmilla", "Panguipulli", "Panquehue", "Papudo", 
  "Paredones", "Parral", "Pedro Aguirre Cerda", "Pelarco", "Pelluhue", "Pemuco", 
  "Pencahue", "Penco", "Peñaflor", "Peñalolén", "Peralillo", "Perquenco", 
  "Petorca", "Peumo", "Pica", "Pichidegua", "Pichilemu", "Pinto", "Pirque", 
  "Pitrufquén", "Placilla", "Portezuelo", "Porvenir", "Pozo Almonte", "Providencia", 
  "Puchuncaví", "Pucón", "Pudahuel", "Puente Alto", "Puerto Aysén", "Puerto Montt", 
  "Puerto Octay", "Puerto Varas", "Pumanque", "Punitaqui", "Punta Arenas", 
  "Puqueldón", "Purén", "Purranque", "Putaendo", "Puyehue", "Queilén", "Quellón", 
  "Quemchi", "Quilaco", "Quilicura", "Quilleco", "Quillón", "Quillota", "Quilpué", 
  "Quinchao", "Quinta de Tilcoco", "Quinta Normal", "Quintero", "Quirihue", 
  "Rancagua", "Ránquil", "Rauco", "Recoleta", "Renaico", "Renca", "Rengo", 
  "Requínoa", "Retiro", "Rinconada", "Río Bueno", "Río Claro", "Río Hurtado", 
  "Río Ibáñez", "Río Negro", "Romeral", "Saavedra", "Sagrada Familia", "Salamanca", 
  "San Antonio", "San Bernardo", "San Carlos", "San Clemente", "San Esteban", 
  "San Fabián", "San Felipe", "San Fernando", "San Ignacio", "San Javier", 
  "San Joaquín", "San José de Maipo", "San Juan De La Costa", "San Miguel", 
  "San Nicolás", "San Pablo", "San Pedro", "San Pedro de la Paz", "San Rafael", 
  "San Ramón", "San Rosendo", "San Vicente", "Santa Bárbara", "Santa Cruz", 
  "Santa Juana", "Santa María", "Santiago", "Santo Domingo", "Sierra Gorda", 
  "Talagante", "Talca", "Talcahuano", "Taltal", "Temuco", "Teno", "Teodoro Schmidt", 
  "Tierra Amarilla", "Til til", "Tirúa", "Tocopilla", "Toltén", "Tomé", 
  "Torres del Paine", "Traiguén", "Treguaco", "Tucapel", "Valdivia", "Vallenar", 
  "Valparaíso", "Vichuquén", "Victoria", "Vicuña", "Vilcún", "Villa Alegre", 
  "Villa Alemana", "Villarrica", "Viña del Mar", "Vitacura", "Yerbas Buenas", 
  "Yumbel", "Yungay", "Zapallar"
];